default_welcome_msg = "Simple Go server!"
echo_buf_size = 8192

[HTTPConfig]

  # 监听的IP和端口，格式host:port, 如0.0.0.0:60066
  host = "0.0.0.0:60066"

[RouteConfig]
  echo = "/echo"

  # 默认的index文件， 如果访问的目录下有该文件， 则直接重定向至该文件
  index = "index.html"
  time = "/time"

[TemplateConfig]
  ListDirTemplate = """
    <html>
    <head><title>{{.Welcome}}</title></head>
    <body>
    <h1>{{.Welcome}}</h1>
    <p>Path: {{.Path}}</p>
    <table>
    <tr><th>Name</th><th>Size</th></tr>
    {{range .Files}}
        <tr>
            <td><a href=\"{{.LinkName}}\">{{.Name}}</a></td>
            <td>{{.Size}} bytes</td>
        </tr>
    {{end}}
    </table>
    </body>
    <html>
    """
  ListDirTemplateFile = "dir.template.html"
